[auth]
allowed_redirect_urls = ["http://localhost:3000/verifikasi-email", "http://localhost:3000/reset-kata-sandi", "https://gleans.my.id/verifikasi-email", "https://gleans.my.id/reset-kata-sandi"]
require_email_verification = true
verify_email_method = "link"
reset_password_method = "link"
disable_signup = false

[auth.password]
min_length = 8
require_number = false
require_lowercase = false
require_uppercase = false
require_special_char = false
