"use client";
import { useEffect, useRef, useState, type ReactNode } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { ArrowLeft, Bold, Italic, Strikethrough, Quote, List, ListOrdered, ChevronDown, ImageIcon } from "lucide-react";
import { z } from "zod";
import { Button } from "@/components/ui/button";
import { ADMIN_BLOG_CATEGORIES, type AdminState } from "@/lib/admin/model";
import { mediaStore, type AdminMedia } from "@/lib/admin/media";
import { useAdmin } from "./provider";
type Blog=AdminState["blogs"][number];
const field="h-11 w-full min-w-0 rounded-full border bg-white px-4 text-sm outline-none focus-visible:ring-2 focus-visible:ring-primary";
const slugify=(value:string)=>value.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
function Label({name,children}:{name:string;children:ReactNode}){return <label className="block space-y-2 text-sm font-medium"><span>{name}</span>{children}</label>;}
function Inline({text}:{text:string}) {return <>{text.split(/(\*\*[^*]+\*\*|\*[^*]+\*|~~[^~]+~~)/g).map((part,i)=>part.startsWith("**")?<strong key={i}>{part.slice(2,-2)}</strong>:part.startsWith("*")?<em key={i}>{part.slice(1,-1)}</em>:part.startsWith("~~")?<s key={i}>{part.slice(2,-2)}</s>:part)}</>;}
function Markdown({content}:{content:string}) {return <div className="space-y-3 text-sm leading-7">{content.split("\n").map((line,i)=>{
 if(/^### /.test(line))return <h3 key={i} className="text-lg font-semibold"><Inline text={line.slice(4)}/></h3>;
 if(/^## /.test(line))return <h2 key={i} className="text-xl font-semibold"><Inline text={line.slice(3)}/></h2>;
 if(/^# /.test(line))return <h1 key={i} className="text-2xl font-semibold"><Inline text={line.slice(2)}/></h1>;
 if(/^> /.test(line))return <blockquote key={i} className="border-l-2 border-primary pl-4 text-muted-foreground"><Inline text={line.slice(2)}/></blockquote>;
 if(/^[-*] /.test(line))return <p key={i} className="pl-3">• <Inline text={line.slice(2)}/></p>;
 if(/^\d+\. /.test(line))return <p key={i} className="pl-3"><Inline text={line}/></p>;
 const image=line.match(/^!\[([^\]]*)\]\(([^)]+)\)$/);if(image&&/^(https?:\/\/|\/images\/)/.test(image[2]))return <img key={i} src={image[2]} alt={image[1]} className="max-w-full rounded-2xl"/>;
 return line?<p key={i} className="break-words"><Inline text={line}/></p>:<div key={i} className="h-2"/>;
 })}</div>;}
export function AdminBlogEditor({id}:{id:string}) {
 const {state,save}=useAdmin();const router=useRouter();const existing=state.blogs.find(b=>b.id===id);
 const [draft,setDraft]=useState<Blog>(()=>existing?{...existing}:{id:`BLOG-${crypto.randomUUID().slice(0,8)}`,title:"",slug:"",summary:"",content:"",category:"Edukasi",author:"Tim Gleans",coverId:"",coverAlt:"",status:"Draft",featured:false});
 const [mode,setMode]=useState("write"),[error,setError]=useState(""),[notice,setNotice]=useState("");const [media,setMedia]=useState<(AdminMedia&{url:string})[]>([]);const textarea=useRef<HTMLTextAreaElement>(null);
 const [publishTime,setPublishTime]=useState(()=>draft.publishAt?new Date(Date.parse(draft.publishAt)+7*3600000).toISOString().slice(0,16):"");
 useEffect(()=>{let live=true;const urls:string[]=[];mediaStore("list").then(items=>{const next=items.map(item=>{const url=item.blob?URL.createObjectURL(item.blob):item.src||"";if(item.blob)urls.push(url);return {...item,url};});if(live)setMedia(next);else urls.forEach(url=>URL.revokeObjectURL(url));}).catch(()=>{if(live)setError("Pustaka media tidak dapat dimuat.");});return()=>{live=false;urls.forEach(url=>URL.revokeObjectURL(url));};},[]);
 if(id!=="baru"&&!existing)return <div className="py-12"><h1 className="text-2xl font-semibold">Artikel tidak ditemukan</h1><Link href="/admin/blog" className="mt-4 inline-block text-primary">Kembali ke Blog</Link></div>;
 function update<K extends keyof Blog>(key:K,value:Blog[K]){setDraft(current=>({...current,[key]:value}));setNotice("");}
 function format(before:string,after="",placeholder="Teks",prefix=false){const node=textarea.current;if(!node)return;const start=node.selectionStart,end=node.selectionEnd;const selected=draft.content.slice(start,end)||placeholder;const replacement=prefix?selected.split("\n").map((line,i)=>`${before==="1. "?`${i+1}. `:before}${line}`).join("\n"):before+selected+after;update("content",draft.content.slice(0,start)+replacement+draft.content.slice(end));requestAnimationFrame(()=>{node.focus();node.setSelectionRange(start+before.length,start+replacement.length-after.length);});}
 function persist(status:Blog["status"]){setError("");try{const publishAt=status==="Terjadwal"?(publishTime?new Date(`${publishTime}:00+07:00`).toISOString():undefined):undefined;save("blogs",{...draft,status,publishAt});setDraft(current=>({...current,status,publishAt}));setNotice(status==="Terjadwal"?"Jadwal tersimpan pada demo. Publikasi otomatis memerlukan integrasi server.":status==="Terbit"?"Artikel diterbitkan pada demo.":status==="Arsip"?"Artikel diarsipkan pada demo.":"Draft disimpan.");if(id==="baru")router.replace(`/admin/blog/${draft.id}`);}catch(e){setError(e instanceof z.ZodError?e.issues.map(issue=>issue.message).join(" · "):e instanceof Error?e.message:"Artikel belum dapat disimpan.");}}
 const cover=media.find(item=>item.id===draft.coverId);
 return <div className="min-w-0"><Link href="/admin/blog" className="mb-6 inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-primary"><ArrowLeft className="size-4"/>Semua artikel</Link>
 <div className="mb-7 flex flex-wrap items-center justify-between gap-4"><div className="flex items-center gap-3"><h1 className="text-2xl font-semibold sm:text-3xl">{id==="baru"?"Tambah artikel":"Edit artikel"}</h1><span className="rounded-full bg-surface px-3 py-1 text-xs text-muted-foreground">{draft.status}</span></div><div className="flex flex-wrap gap-2"><Button variant="ghost" className="h-11 rounded-full" onClick={()=>persist("Arsip")}>Arsipkan</Button><Button variant="outline" className="h-11 rounded-full" onClick={()=>persist("Draft")}>Simpan draft</Button><Button variant="secondary" className="h-11 rounded-full" onClick={()=>persist("Terjadwal")}>Jadwalkan</Button><Button className="h-11 rounded-full" onClick={()=>persist("Terbit")}>Terbitkan</Button></div></div>
 {error&&<p role="alert" className="mb-5 rounded-xl bg-red-50 p-4 text-sm text-destructive">{error}</p>}{notice&&<p role="status" className="mb-5 rounded-xl bg-accent p-4 text-sm text-primary">{notice}</p>}
 <div className="grid min-w-0 gap-6 xl:grid-cols-[minmax(0,1fr)_300px]"><div className="min-w-0 space-y-5">
 <Label name="Judul"><input className={field} value={draft.title} placeholder="Judul artikel" onChange={e=>{const title=e.target.value;setDraft(current=>({...current,title,slug:!current.slug||current.slug===slugify(current.title)?slugify(title):current.slug}));setNotice("");}}/></Label>
 <Label name="Deskripsi"><textarea className="min-h-24 w-full rounded-2xl border bg-white p-4 text-sm font-normal outline-none focus-visible:ring-2 focus-visible:ring-primary" maxLength={500} value={draft.summary} onChange={e=>update("summary",e.target.value)} placeholder="Ringkasan singkat artikel"/></Label>
 <div className="grid gap-4 sm:grid-cols-2"><Label name="Kategori"><div className="relative"><select className={field+" appearance-none pr-10"} value={draft.category} onChange={e=>update("category",e.target.value as Blog["category"])}>{ADMIN_BLOG_CATEGORIES.map(c=><option key={c}>{c}</option>)}</select><ChevronDown className="pointer-events-none absolute right-4 top-3.5 size-4 text-muted-foreground"/></div></Label><Label name="Penulis"><input className={field} value={draft.author} onChange={e=>update("author",e.target.value)}/></Label></div>
 <Label name="Slug"><div className="flex items-center gap-2"><span className="font-normal text-muted-foreground">/blog/</span><input className={field} value={draft.slug} onChange={e=>update("slug",e.target.value)}/></div></Label>
 <div><div className="mb-3 inline-flex rounded-full bg-surface p-1" role="tablist" aria-label="Mode editor">{[["write","Tulis (Markdown)"],["preview","Preview"]].map(([value,label])=><button key={value} role="tab" aria-selected={mode===value} className={`rounded-full px-4 py-2 text-sm ${mode===value?"bg-white font-medium shadow-sm":"text-muted-foreground"}`} onClick={()=>setMode(value)}>{label}</button>)}</div>
 {mode==="write"?<><div className="mb-3 flex flex-wrap items-center gap-1 rounded-2xl bg-surface p-2"><select aria-label="Gaya teks" className="h-9 rounded-full bg-transparent px-3 text-sm" value="" onChange={e=>{format(e.target.value,"","Judul",true);}}><option value="" disabled>Gaya teks</option><option value="# ">Judul 1</option><option value="## ">Judul 2</option><option value="### ">Judul 3</option></select>{[{label:"Tebal",Icon:Bold,before:"**",after:"**"},{label:"Miring",Icon:Italic,before:"*",after:"*"},{label:"Coret",Icon:Strikethrough,before:"~~",after:"~~"},{label:"Kutipan",Icon:Quote,before:"> ",prefix:true},{label:"Daftar poin",Icon:List,before:"- ",prefix:true},{label:"Daftar nomor",Icon:ListOrdered,before:"1. ",prefix:true}].map(({label,Icon,before,after,prefix})=><Button key={label} variant="ghost" size="icon" aria-label={label} onClick={()=>format(before,after,"Teks",prefix)}><Icon className="size-4"/></Button>)}</div><textarea ref={textarea} aria-label="Isi artikel" className="min-h-[420px] w-full rounded-2xl border bg-white p-4 font-mono text-sm leading-7 outline-none focus-visible:ring-2 focus-visible:ring-primary" value={draft.content} onChange={e=>update("content",e.target.value)} placeholder="Tulis isi artikel di sini."/></>:<article className="min-h-[420px] rounded-2xl border p-5">{cover&&<img src={cover.url} alt={draft.coverAlt} className="mb-5 aspect-video w-full rounded-2xl object-cover"/>}<p className="mb-2 text-xs text-muted-foreground">{draft.category} · {draft.author}</p><h2 className="mb-3 text-2xl font-semibold">{draft.title||"Judul artikel"}</h2><p className="mb-6 text-sm text-muted-foreground">{draft.summary}</p>{draft.content?<Markdown content={draft.content}/>:<p className="text-sm text-muted-foreground">Isi artikel belum ditulis.</p>}</article>}</div></div>
 <aside className="min-w-0 space-y-6 self-start rounded-[24px] bg-surface p-5"><Label name="Waktu publikasi (WIB)"><input type="datetime-local" className={field} value={publishTime} onChange={e=>setPublishTime(e.target.value)}/></Label><p className="-mt-4 text-xs leading-relaxed text-muted-foreground">Pilih waktu mendatang lalu klik Jadwalkan, atau klik Terbitkan untuk terbit sekarang.</p><div className="space-y-3"><p className="text-sm font-medium">Gambar cover</p>{cover?<img src={cover.url} alt={draft.coverAlt} className="aspect-video w-full rounded-2xl border object-cover"/>:<div className="flex aspect-video items-center justify-center rounded-2xl border bg-white text-muted-foreground"><ImageIcon className="size-8"/></div>}<Label name="Pilih dari pustaka media"><select className={field} value={draft.coverId} onChange={e=>update("coverId",e.target.value)}><option value="">Tanpa cover</option>{media.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></Label><Label name="Teks alternatif cover"><input className={field} value={draft.coverAlt} onChange={e=>update("coverAlt",e.target.value)} placeholder="Deskripsi gambar"/></Label><Link href="/admin/pengaturan" className="inline-block text-xs text-primary">Kelola pustaka media</Link></div><div className="flex items-center justify-between gap-3"><span className="text-sm font-medium">Unggulan di homepage</span><button role="switch" aria-label="Unggulan di homepage" aria-checked={draft.featured} onClick={()=>update("featured",!draft.featured)} className={`inline-flex h-6 w-11 shrink-0 rounded-full p-0.5 ${draft.featured?"bg-primary":"bg-muted"}`}><span className={`size-5 rounded-full bg-white shadow-sm transition-transform ${draft.featured?"translate-x-5":""}`}/></button></div></aside>
 </div></div>;
}
