"use client";
import { createContext, useContext, useEffect, useState, type ReactNode } from "react";
import { toast } from "sonner";
import { ADMIN_STORAGE_KEY, adminSchema, initialAdmin, upgradeAdminDemo, inviteDemoAdmin, revokeDemoAdmin, saveAdminRecord, type AdminState, type Collection, type RecordData } from "@/lib/admin/model";
const Context = createContext<{ state: AdminState; ready: boolean; error: string; save: (collection: Collection, record: RecordData, reason?: string) => void; configure: (settings: AdminState["settings"]) => void; invite: (member:{name:string;email:string;role:"Editor"|"Operator"})=>void; log:(action:string,object:string)=>void; revoke:(id:string)=>void; clearActivity:()=>void; reset: () => void } | null>(null);
export function AdminProvider({children}:{children:ReactNode}) {
  const [state,setState]=useState(initialAdmin); const [ready,setReady]=useState(false); const [error,setError]=useState("");
  useEffect(()=>{try { const raw=localStorage.getItem(ADMIN_STORAGE_KEY); if(raw) setState(upgradeAdminDemo(adminSchema.parse(JSON.parse(raw)))); } catch {setError("Data demo tidak dapat dipulihkan. Data contoh digunakan.");} setReady(true);},[]);
  useEffect(()=>{if(!ready)return;try{localStorage.setItem(ADMIN_STORAGE_KEY,JSON.stringify(state));}catch{setError("Penyimpanan browser tidak tersedia. Perubahan hanya berlaku selama halaman ini terbuka.");}},[state,ready]);
  function save(collection:Collection,record:RecordData,reason="") {const next=saveAdminRecord(state,collection,record,reason);setState(next);toast.success("Perubahan demo disimpan.");}
  function configure(settings:AdminState["settings"]) {const parsed=adminSchema.shape.settings.parse(settings);if(parsed.maxWords<parsed.minWords)throw new Error("Batas maksimal kata harus lebih besar dari batas minimal.");setState({...state,settings:parsed,activity:[{id:crypto.randomUUID(),action:"Memperbarui pengaturan website",actor:"Admin Demo",object:"Pengaturan",at:new Date().toISOString()},...state.activity].slice(0,100)});toast.success("Pengaturan demo disimpan.");}
  return <Context.Provider value={{state,ready,error,save,configure,revoke:id=>{setState(revokeDemoAdmin(state,id));toast.success("Akses admin demo dicabut.");},invite:member=>{setState(inviteDemoAdmin(state,member));toast.success("Undangan demo disimpan. Tidak ada email yang dikirim.");},log:(action,object)=>setState(current=>({...current,activity:[{id:crypto.randomUUID(),action,object,actor:"Admin Demo",at:new Date().toISOString()},...current.activity].slice(0,100)})),clearActivity:()=>setState(current=>({...current,activity:[]})),reset:()=>setState(initialAdmin())}}>{children}</Context.Provider>;
}
export function useAdmin(){const value=useContext(Context);if(!value)throw new Error("Admin provider missing");return value;}
