"use client";

import { useEffect, useRef, useState } from "react";
import { Copy, ImageIcon, Trash2, Upload, UserPlus, UserMinus, MoreVertical } from "lucide-react";
import Image from "next/image";
import { toast } from "sonner";
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuItem } from "@/components/ui/dropdown-menu";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { mediaStore, validateMedia, type AdminMedia } from "@/lib/admin/media";
import { useAdmin } from "./provider";
import { card } from "./overview";

const input="h-11 w-full min-w-0 rounded-full border bg-white px-4 text-sm outline-none focus-visible:ring-2 focus-visible:ring-primary";
function errorMessage(error:unknown){return error instanceof Error?error.message:"Perubahan tidak dapat disimpan.";}

export function AdminSettings(){
 const {state,invite,revoke,clearActivity}=useAdmin();
 const [revokeId,setRevokeId]=useState<string|null>(null); const revokeMember=state.admins.find(a=>a.id===revokeId);
 const [inviteOpen,setInviteOpen]=useState(false);const [clearOpen,setClearOpen]=useState(false);
 const [name,setName]=useState("");const [email,setEmail]=useState("");const [role,setRole]=useState<"Editor"|"Operator">("Editor");const [error,setError]=useState("");
 return <>
  <div className="mb-7"><h1 className="text-2xl font-semibold sm:text-3xl">Pengaturan</h1><p className="mt-2 text-sm text-muted-foreground">Kelola admin, log aktivitas, dan pustaka media Gleans.</p></div>
  <Tabs defaultValue="admin" className="min-w-0 gap-7">
   <TabsList className="h-10 group-data-horizontal/tabs:h-10 rounded-full bg-surface p-1"><TabsTrigger className="rounded-full px-5 py-2" value="admin">Admin</TabsTrigger><TabsTrigger className="rounded-full px-5 py-2" value="activity">Aktivitas</TabsTrigger><TabsTrigger className="rounded-full px-5 py-2" value="media">Media</TabsTrigger></TabsList>
   <TabsContent className="min-w-0" value="admin"><section className={card}><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><h2 className="font-semibold">Daftar admin</h2><Button size="pill-sm" onClick={()=>{setName("");setEmail("");setError("");setRole("Editor");setInviteOpen(true);}}><UserPlus className="size-4"/>Undang</Button></div><div className="divide-y">{state.admins.filter(admin=>admin.status!=="Dicabut").map(a=><div key={a.id} className="flex flex-wrap items-center justify-between gap-4 py-4"><div className="min-w-0"><p className="break-words text-sm font-semibold">{a.name}</p><p className="mt-1 break-all text-xs text-muted-foreground">{a.email}</p></div><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-accent px-3 py-1 text-xs text-primary">{a.role}</span><span className={`rounded-full px-3 py-1 text-xs ${a.status==="Dicabut"?"bg-red-50 text-red-700":"bg-surface text-muted-foreground"}`}>{a.status}</span>{a.role!=="Owner"&&a.status!=="Dicabut"&&<DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" size="icon" className="rounded-full" aria-label={`Menu admin ${a.name}`}><MoreVertical className="size-4"/></Button></DropdownMenuTrigger><DropdownMenuContent align="end" className="min-w-40 rounded-xl"><DropdownMenuItem variant="destructive" onSelect={()=>{setError("");setRevokeId(a.id);}}><UserMinus className="size-4"/>Remove akses</DropdownMenuItem></DropdownMenuContent></DropdownMenu>}</div></div>)}</div></section></TabsContent>
   <TabsContent className="min-w-0" value="activity"><section className="min-w-0 w-full"><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><p className="text-sm text-muted-foreground">{state.activity.length} aktivitas terakhir</p><Button variant="outline" size="pill-sm" disabled={!state.activity.length} onClick={()=>setClearOpen(true)}><Trash2 className="size-4"/>Hapus riwayat</Button></div><div role="region" aria-label="Tabel aktivitas" tabIndex={0} className="overflow-x-auto rounded-2xl border focus-visible:ring-2 focus-visible:ring-primary"><table className="w-full min-w-[700px] table-fixed text-sm"><colgroup><col className="w-[24%]"/><col className="w-[18%]"/><col className="w-[32%]"/><col className="w-[26%]"/></colgroup><caption className="sr-only">Log aktivitas admin demo</caption><thead className="bg-surface text-xs text-muted-foreground"><tr>{["WAKTU","PELAKU","TINDAKAN","OBJEK"].map(x=><th key={x} scope="col" className="px-4 py-4 text-left font-medium">{x}</th>)}</tr></thead><tbody className="divide-y">{state.activity.map(a=><tr key={a.id}><td className="whitespace-nowrap px-4 py-4 text-xs">{new Intl.DateTimeFormat("id-ID",{dateStyle:"medium",timeStyle:"short",timeZone:"Asia/Jakarta"}).format(new Date(a.at))} WIB</td><td className="break-words px-4 py-4 align-top">{a.actor}</td><td className="break-words px-4 py-4 align-top">{a.action}</td><td className="break-words px-4 py-4 align-top [overflow-wrap:anywhere]">{a.object}</td></tr>)}{!state.activity.length&&<tr><td colSpan={4} className="px-4 py-12 text-center text-muted-foreground">Belum ada aktivitas. Perubahan demo akan muncul di sini.</td></tr>}</tbody></table></div></section></TabsContent>
   <TabsContent className="min-w-0" value="media"><MediaLibrary/></TabsContent>
  </Tabs>
  <Dialog open={inviteOpen} onOpenChange={setInviteOpen}><DialogContent className="rounded-[24px]"><DialogHeader><DialogTitle>Undang admin</DialogTitle><DialogDescription>Simulasi undangan untuk demo. Tidak mengirim email atau memberikan akses nyata.</DialogDescription></DialogHeader><form className="space-y-4" onSubmit={e=>{e.preventDefault();try{invite({name,email,role});setInviteOpen(false);}catch(e){setError(errorMessage(e));}}}><label className="block space-y-2 text-sm"><span>Nama admin</span><input required maxLength={200} className={input} value={name} onChange={e=>setName(e.target.value)}/></label><label className="block space-y-2 text-sm"><span>Email admin</span><input required type="email" className={input} value={email} onChange={e=>setEmail(e.target.value)}/></label><label className="block space-y-2 text-sm"><span>Peran</span><select className={input} value={role} onChange={e=>setRole(e.target.value as typeof role)}><option>Editor</option><option>Operator</option></select></label><p className="text-xs text-muted-foreground">{role==="Editor"?"Editor mengelola artikel dan promosi.":"Operator menangani operasional pesanan."}</p>{error&&<p role="alert" className="text-sm text-destructive">{error}</p>}<div className="grid grid-cols-2 gap-3"><Button type="button" variant="outline" size="pill-sm" className="w-full" onClick={()=>setInviteOpen(false)}>Batal</Button><Button type="submit" size="pill-sm" className="w-full">Undang</Button></div></form></DialogContent></Dialog>
  <Dialog open={!!revokeId} onOpenChange={v=>{if(!v)setRevokeId(null);}}><DialogContent className="rounded-[24px]"><DialogHeader><DialogTitle>Cabut akses admin?</DialogTitle><DialogDescription>{revokeMember?.name} ({revokeMember?.email}). {revokeMember?.status==="Diundang"?"Undangan demo akan dibatalkan.":"Status akses admin demo akan dicabut."} Admin akan dihapus dari daftar dan dapat diundang kembali. Riwayat pencabutan tetap tersimpan di Aktivitas. Perubahan ini hanya berlaku pada demo.</DialogDescription></DialogHeader>{error&&<p role="alert" className="text-sm text-destructive">{error}</p>}<div className="flex justify-end gap-3"><Button variant="outline" size="pill-sm" onClick={()=>setRevokeId(null)}>Batal</Button><Button variant="destructive" size="pill-sm" onClick={()=>{if(!revokeId)return;try{revoke(revokeId);setRevokeId(null);}catch(e){setError(errorMessage(e));}}}>Cabut akses</Button></div></DialogContent></Dialog>
  <Dialog open={clearOpen} onOpenChange={setClearOpen}><DialogContent className="rounded-[24px]"><DialogHeader><DialogTitle>Hapus riwayat demo?</DialogTitle><DialogDescription>Log aktivitas pada browser ini akan dikosongkan. Data artikel, promosi, dan admin tetap tersedia.</DialogDescription></DialogHeader><div className="flex justify-end gap-3"><Button variant="outline" size="pill-sm" onClick={()=>setClearOpen(false)}>Batal</Button><Button variant="destructive" size="pill-sm" onClick={()=>{clearActivity();setClearOpen(false);toast.success("Riwayat demo dikosongkan.");}}>Hapus riwayat demo</Button></div></DialogContent></Dialog>
 </>;
}

function MediaLibrary(){
 const {log}=useAdmin();const fileInput=useRef<HTMLInputElement>(null);
 const [items,setItems]=useState<AdminMedia[]>([]);const [urls,setUrls]=useState<Record<string,string>>({});const [ready,setReady]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [remove,setRemove]=useState<AdminMedia|null>(null);
 useEffect(()=>{let active=true;mediaStore("list").then(data=>{if(active)setItems(data);}).catch(e=>{if(active)setError(errorMessage(e));}).finally(()=>{if(active)setReady(true);});return()=>{active=false;};},[]);
 useEffect(()=>{const generated: string[]=[];const next:Record<string,string>={};for(const m of items){if(m.blob){const url=URL.createObjectURL(m.blob);generated.push(url);next[m.id]=url;}else if(m.src)next[m.id]=m.src;}setUrls(next);return()=>generated.forEach(url=>URL.revokeObjectURL(url));},[items]);
 async function upload(file:File){setBusy(true);setError("");try{validateMedia(file);const id=crypto.randomUUID();const bitmap=await createImageBitmap(file);bitmap.close();const next=await mediaStore("put",{id,name:file.name,alt:file.name,size:file.size,blob:file});setItems(next);log("Mengunggah media",file.name);toast.success("Gambar demo disimpan di browser.");}catch(e){setError(errorMessage(e));}finally{setBusy(false);if(fileInput.current)fileInput.current.value="";}}
 async function copy(item:AdminMedia){try{let value:string;if(item.blob)value=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(new Error("Gambar tidak dapat dibaca."));reader.readAsDataURL(item.blob!);});else value=new URL(item.src!,window.location.origin).href;await navigator.clipboard.writeText(value);toast.success("Tautan gambar disalin. Unggahan lokal memakai data URL.");}catch{toast.error("Tautan gambar tidak dapat disalin.");}}
 return <section className="min-w-0 w-full"><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">Pustaka media</h2><p className="mt-2 text-xs leading-relaxed text-muted-foreground">Gambar cover artikel dan promosi. PNG, JPG, WebP, atau GIF, maksimal 10 MB.</p></div><Button size="pill-sm" disabled={busy||!ready} onClick={()=>fileInput.current?.click()}><Upload className="size-4"/>{busy?"Menyimpan…":"Unggah"}</Button><input ref={fileInput} type="file" accept="image/png,image/jpeg,image/webp,image/gif" aria-label="Pilih gambar media" className="sr-only" onChange={e=>{const file=e.target.files?.[0];if(file)void upload(file);}}/></div>{error&&<p role="alert" className="mb-4 text-sm text-destructive">{error}</p>}{!ready?<p className="py-10 text-center text-sm text-muted-foreground">Memuat media…</p>:<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{items.map(m=><article key={m.id} className="overflow-hidden rounded-[16px] border"><div className="aspect-video bg-surface">{urls[m.id]&&<Image unoptimized width={640} height={360} src={urls[m.id]} alt={m.alt} className="h-full w-full rounded-[12px] object-cover"/>}</div><div className="p-4"><p className="truncate text-sm font-medium" title={m.name}>{m.name}</p><p className="mt-1 text-xs text-muted-foreground">{m.size?`${(m.size/1024/1024).toFixed(2)} MB`:"Gambar contoh"}</p><div className="mt-3 flex justify-end gap-1"><Button variant="ghost" size="icon" aria-label={`Salin tautan ${m.name}`} onClick={()=>void copy(m)}><Copy className="size-4"/></Button><Button variant="ghost" size="icon" aria-label={`Hapus media ${m.name}`} onClick={()=>setRemove(m)}><Trash2 className="size-4"/></Button></div></div></article>)}</div>}{ready&&!items.length&&<div className="py-12 text-center"><ImageIcon className="mx-auto mb-3 size-8 text-muted-foreground"/><p className="text-sm text-muted-foreground">Belum ada media. Unggah gambar pertama.</p></div>}
 <Dialog open={!!remove} onOpenChange={v=>{if(!v)setRemove(null);}}><DialogContent className="rounded-[24px]"><DialogHeader><DialogTitle>Hapus gambar demo?</DialogTitle><DialogDescription>{remove?.name} akan dihapus dari pustaka media browser ini.</DialogDescription></DialogHeader><div className="flex justify-end gap-3"><Button variant="outline" size="pill-sm" onClick={()=>setRemove(null)}>Batal</Button><Button variant="destructive" size="pill-sm" disabled={busy} onClick={async()=>{if(!remove)return;setBusy(true);try{setItems(await mediaStore("delete",remove.id));log("Menghapus media",remove.name);setRemove(null);}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}}>Hapus gambar</Button></div></DialogContent></Dialog>
 </section>;
}
