"use client";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { useEffect, useState, type ReactNode } from "react";
import { LayoutDashboard, ReceiptText, Users, Wallet, BookOpen, Megaphone, Settings, Menu, RotateCcw, ShieldCheck, MoreVertical, Monitor, Sun, Moon, LogOut } from "lucide-react";
import { Logo } from "@/components/brand/logo";
import { Button } from "@/components/ui/button";
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription, SheetTrigger } from "@/components/ui/sheet";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { AdminProvider,useAdmin } from "./provider";
import { AdminNotifications } from "./notifications";
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuLabel, DropdownMenuRadioGroup, DropdownMenuRadioItem, DropdownMenuSeparator, DropdownMenuItem } from "@/components/ui/dropdown-menu";
import { cn } from "@/lib/utils";
export const adminLinks=[{href:"/admin",label:"Ringkasan",icon:LayoutDashboard},{href:"/admin/pesanan",label:"Pesanan",icon:ReceiptText},{href:"/admin/pelanggan",label:"Pelanggan",icon:Users},{href:"/admin/paket-transaksi",label:"Paket & Transaksi",icon:Wallet},{href:"/admin/blog",label:"Blog",icon:BookOpen},{href:"/admin/promosi",label:"Promosi",icon:Megaphone},{href:"/admin/pengaturan",label:"Pengaturan",icon:Settings}];
function Navigation({close}:{close?:()=>void}){const path=usePathname();return <nav aria-label="Menu admin" className="space-y-2">{adminLinks.map(x=><Link key={x.href} href={x.href} onClick={close} aria-current={(path===x.href||(x.href!=="/admin"&&path.startsWith(x.href+"/")))?"page":undefined} className={cn("flex items-center gap-3 rounded-xl px-4 py-3 text-sm hover:bg-accent",(path===x.href||(x.href!=="/admin"&&path.startsWith(x.href+"/")))?"bg-accent font-medium text-primary":"text-muted-foreground")}><x.icon className="size-5 shrink-0"/>{x.label}</Link>)}</nav>;}
type Appearance = "system" | "light" | "dark";
function AdminProfile({theme,onTheme,close}:{theme:Appearance;onTheme:(theme:Appearance)=>void;close?:()=>void}) {
 const {state}=useAdmin();const router=useRouter();
 const profile=state.admins.find(a=>a.role==="Owner"&&a.status==="Aktif");
 return <div className="mt-auto border-t pt-4"><div className="flex min-w-0 items-center gap-3">
 {/* eslint-disable-next-line @next/next/no-img-element */}
 <img src="/images/admin-profile.png" alt="Logo Gleans" width={44} height={44} className="size-11 shrink-0 rounded-full object-cover"/>
 <div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{profile?.name||"Admin Demo"}</p><p className="mt-1 truncate text-xs text-muted-foreground" title={profile?.email}>{profile?.email||"owner@example.com"}</p></div>
 <DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" size="icon" aria-label="Menu profil admin" className="shrink-0 rounded-full"><MoreVertical className="size-5"/></Button></DropdownMenuTrigger><DropdownMenuContent side="top" align="end" sideOffset={12} className="w-52 rounded-2xl p-1.5"><DropdownMenuLabel>Tampilan</DropdownMenuLabel><DropdownMenuRadioGroup value={theme} onValueChange={value=>onTheme(value as Appearance)}>{[{value:"system",label:"System",icon:Monitor},{value:"light",label:"Light",icon:Sun},{value:"dark",label:"Dark",icon:Moon}].map(item=><DropdownMenuRadioItem key={item.value} value={item.value} className="min-h-10 cursor-pointer gap-3 rounded-xl px-3 pr-9"><item.icon className="size-4"/>{item.label}</DropdownMenuRadioItem>)}</DropdownMenuRadioGroup><DropdownMenuSeparator/><DropdownMenuItem variant="destructive" className="min-h-10 cursor-pointer gap-3 rounded-xl px-3" onSelect={()=>{close?.();router.push("/masuk");}}><LogOut className="size-4"/>Keluar</DropdownMenuItem></DropdownMenuContent></DropdownMenu>
 </div></div>;
}
function Shell({children}:{children:ReactNode}){const {ready,error,reset}=useAdmin();const [open,setOpen]=useState(false);const [resetOpen,setResetOpen]=useState(false);const [theme,setTheme]=useState<Appearance>("system");const [themeReady,setThemeReady]=useState(false);
 useEffect(()=>{try{const stored=localStorage.getItem("gleans:admin-appearance");if(stored==="system"||stored==="light"||stored==="dark")setTheme(stored);}catch{}setThemeReady(true);},[]);
 useEffect(()=>{if(!themeReady)return;const media=window.matchMedia("(prefers-color-scheme: dark)");function apply(){document.documentElement.dataset.adminTheme=theme==="system"?(media.matches?"dark":"light"):theme;}apply();media.addEventListener("change",apply);try{localStorage.setItem("gleans:admin-appearance",theme);}catch{}return()=>{media.removeEventListener("change",apply);delete document.documentElement.dataset.adminTheme;};},[theme,themeReady]);
 return <div className="admin-shell min-h-dvh bg-white lg:pl-[320px]"><aside className="fixed inset-y-0 left-0 hidden w-[320px] flex-col overflow-y-auto border-r bg-white p-5 lg:flex"><Link href="/admin" aria-label="Gleans Admin" className="mb-9 mt-3 px-3"><Logo className="h-8"/></Link><p className="mb-4 px-4 text-xs tracking-wider text-muted-foreground">MENU ADMIN</p><Navigation/><AdminProfile theme={theme} onTheme={setTheme}/></aside><header className="flex h-20 items-center justify-between border-b px-4 sm:px-8"><Sheet open={open} onOpenChange={setOpen}><SheetTrigger asChild><Button variant="ghost" size="icon" className="lg:hidden" aria-label="Buka menu admin"><Menu/></Button></SheetTrigger><SheetContent side="left" className="admin-shell flex w-[min(320px,90vw)] flex-col overflow-y-auto p-5"><SheetHeader className="mb-6 px-0"><SheetTitle>Gleans Admin</SheetTitle><SheetDescription>Menu dashboard admin demo.</SheetDescription></SheetHeader><Navigation close={()=>setOpen(false)}/><div className="mt-auto pt-8"><AdminProfile theme={theme} onTheme={setTheme} close={()=>setOpen(false)}/></div></SheetContent></Sheet><div className="ml-auto flex items-center gap-3"><AdminNotifications/><div className="flex items-center gap-2 rounded-full border px-3 py-2 text-sm"><ShieldCheck className="size-5 text-primary"/><span>Admin Demo</span></div></div></header><main className="mx-auto max-w-[1280px] p-4 sm:p-8"><div className="mb-7 flex flex-wrap items-center justify-between gap-3 rounded-2xl bg-accent/60 p-4"><div className="flex min-w-0 items-center gap-3"><span className="shrink-0 rounded-full bg-white px-3 py-1 text-xs font-medium text-primary">Mode demo</span><p className="text-xs leading-relaxed text-muted-foreground">Data contoh. Perubahan tidak diterapkan pada website atau akun pengguna.</p></div><Button variant="ghost" className="text-xs text-primary" onClick={()=>setResetOpen(true)}><RotateCcw className="size-3.5"/>Reset demo</Button></div>{error&&<p role="alert" className="mb-4 text-sm text-destructive">{error}</p>}{ready?children:<p role="status" className="py-20 text-center">Menyiapkan admin…</p>}</main><Dialog open={resetOpen} onOpenChange={setResetOpen}><DialogContent className="rounded-[24px]"><DialogHeader><DialogTitle>Reset demo admin?</DialogTitle><DialogDescription>Perubahan admin demo akan dikembalikan ke data contoh. Dashboard pengguna tetap tersedia.</DialogDescription></DialogHeader><div className="flex justify-end gap-3"><Button variant="outline" onClick={()=>setResetOpen(false)}>Batal</Button><Button onClick={()=>{reset();setResetOpen(false);}}>Pulihkan data contoh</Button></div></DialogContent></Dialog></div>;}
export function AdminShell({children}:{children:ReactNode}){return <AdminProvider><Shell>{children}</Shell></AdminProvider>;}
