"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import Image from "next/image";
import { Wallet, Layers, Clock3, ArrowUpRight, Plus } from "lucide-react";
import { useDashboard } from "./provider";
import { Panel, Status, Empty, dateLabel } from "./shared";
import { Button } from "@/components/ui/button";
import { formatRupiah } from "@/lib/format";
import { PRODUCTS } from "@/lib/site";
export function DashboardOverview() {
  const { state } = useDashboard();
  const [greeting, setGreeting] = useState("Selamat Datang");
  useEffect(() => {
    const hour = new Date().getHours();
    setGreeting(hour >= 5 && hour < 11 ? "Selamat Pagi" : hour >= 11 && hour < 15 ? "Selamat Siang" : hour >= 15 && hour < 18 ? "Selamat Sore" : "Selamat Malam");
  }, []);
  const stats = [{ label: "TOTAL SALDO", value: formatRupiah(state.balance), icon: Wallet, href: "/dashboard/paket-saldo", action: "Isi saldo" }, { label: "TOTAL KUOTA", value: `${state.quota} pemeriksaan`, icon: Layers, href: "/dashboard/paket-saldo", action: "Lihat paket" }, { label: "TOTAL PESANAN", value: String(state.orders.length), icon: Clock3, href: "/dashboard/pesanan", action: "Lihat pesanan" }];
  return <><section aria-label="Sapaan pengguna" className="mb-7 flex flex-wrap items-center justify-between gap-5 rounded-[24px] bg-[#101D42] p-6 text-white sm:p-8"><div className="min-w-0"><h1 className="break-words text-2xl font-semibold tracking-tight sm:text-3xl">{greeting}</h1><p className="mt-2 text-sm leading-relaxed text-white/75">Lanjutkan langkah kecil untuk tulisan yang lebih baik.</p></div><Button asChild size="pill-sm" className="shrink-0"><Link href="/dashboard/pesanan?baru=1"><Plus />Pesanan demo</Link></Button></section><div className="grid gap-4 md:grid-cols-3">{stats.map(s => <Panel key={s.label} className="border border-border bg-white"><div className="flex items-center justify-between"><p className="text-sm text-muted-foreground">{s.label}</p><s.icon className="size-5" strokeWidth={1.5} /></div><p className="mt-5 text-2xl font-semibold tracking-tight">{s.value}</p><Link href={s.href} className="mt-6 flex items-center gap-1 text-sm text-primary">{s.action}<ArrowUpRight className="size-4" /></Link></Panel>)}</div><div className="mt-8"><h2 className="mb-4 text-lg font-semibold">Apa yang ingin kamu kerjakan?</h2><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{PRODUCTS.filter(p => p.name !== "Gleans Writer").map(p => <div key={p.name} className="flex min-w-0 flex-col rounded-2xl border p-4"><Image src={p.icon} alt="" width={32} height={32} className="mb-4 size-8" /><div className="flex flex-wrap items-center gap-2"><h3 className="text-sm font-medium">{p.name}</h3>{p.soon && <span className="text-[10px] text-muted-foreground">Segera hadir</span>}</div><p className="mt-2 flex-1 text-xs leading-relaxed text-muted-foreground">{p.name === "Gleans Shield" ? "Periksa dokumen melalui layanan Shield." : p.description}</p>{!p.soon && <Link href={p.href} className="mt-4 flex items-center gap-1 text-xs text-primary">Buka layanan<ArrowUpRight className="size-3.5" /></Link>}</div>)}</div></div><section aria-label="Pesanan terbaru" className="mt-8 min-w-0"><div className="mb-4 flex items-center justify-between"><h2 className="font-semibold">Pesanan terbaru</h2><Link href="/dashboard/pesanan" className="text-xs text-primary">Lihat semua</Link></div>{state.orders.length ? <div className="flex flex-col gap-3">{state.orders.slice(0,5).map(order => <Link href={`/dashboard/pesanan?detail=${order.id}`} key={order.id} className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border bg-white p-4 hover:ring-1 hover:ring-primary"><div className="min-w-0"><p className="break-words text-sm font-medium">{order.document}</p><p className="mt-1 text-xs text-muted-foreground">Shield · {dateLabel(order.at)}</p></div><Status order={order} /></Link>)}</div> : <Empty title="Belum ada pesanan" description="Buat pesanan demo untuk mencoba alur pemeriksaan Shield." />}</section></>;
}
